# fly.toml app configuration file generated for potocki-webhook on 2023-06-19T12:11:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "potocki-webhook"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
